spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesapp
    username: notesapp
    password: notesapp
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update